shop/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:product_id>/',
         views.basket_add,
         name='basket_add'),
    path('remove/<int:product_id>/',
         views.basket_remove,
         name='basket_remove'),
]

shop/myshop/urls.py
from django.urls import path
from . import views


app_name = 'myshop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),


]

shop/myshop_api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('product', ProductListAPIView.as_view())
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('users.urls')),
    path('basket/', include("basket.urls", namespace='basket')),
    path('myshop', include('myshop.urls', namespace='shop')),
    path('api/', include("myshop_api.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api-auth/', include('rest_framework.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/users/urls.py
from django.urls import path
from . import views
urlpatterns = [

 path('', views.home, name = "home"),
 path("register/", views.SignUp.as_view(), name="signup"),
]

shop/basket/models.py
from django.db import models

# Create your models here.

shop/myshop/models.py
from django.db import models
from django.urls import reverse


SEX = [
    ('m', 'male'),
    ('f', 'female')
]

class Users(models.Model):
    name = models.CharField(max_length=100,verbose_name='имя')
    surname = models.CharField(max_length=100,verbose_name='фамилия')
    age = models.IntegerField(verbose_name='возраст')
    sex = models.CharField(max_length=1, choices=SEX,verbose_name='пол')
    email = models.EmailField(null=True,verbose_name='почта')
    city = models.CharField(max_length=100, default='Minsk',verbose_name='город')

    def __str__(self):
        return self.name



class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])

shop/users/models.py
from django.db import models

# Create your models here.

shop/basket/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class BasketAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop/basket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myshop.models import Product
from .basket import Basket
from .forms import BasketAddProductForm


@require_POST
def basket_add(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    form = BasketAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        basket.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('basket:basket_detail')


def basket_remove(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.remove(product)
    return redirect('basket:basket_detail')


def basket_detail(request):
    basket = Basket(request)
    for item in basket:
        item['update_quantity_form'] = BasketAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'basket/detail.html', {'basket': basket})

shop/myshop/views.py
from basket.forms import BasketAddProductForm
from .models import Category, Product
from django.shortcuts import render, get_object_or_404




def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    basket_product_form = BasketAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'basket_product_form': basket_product_form})

shop/myshop_api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from myshop.models import Product
from .serializers import ProductSerializer
from rest_framework import status
from django.http import Http404
from rest_framework import generics
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token


# class ProductAPIView(APIView):
#     def get(self, request, format=None):
#         return Response({"massage": "Hello world"})

class ProductListAPIView(generics.ListCreateAPIView):
    # authentication_classes = [BasicAuthentication]
    # permission_classes = [IsAuthenticated]
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

class ProductListAPIViewDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

# class CustomAuthToken(ObtainAuthToken):
#
#     def post(self, request, *args, **kwargs):
#         serializer = self.serializer_class(data=request.data,
#                                            context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         user = serializer.validated_data['user']
#         token, created = Token.objects.get_or_create(user=user)
#         return Response({
#             'token': token.key,
#             'user_id': user.pk,
#             'email': user.email
#         })

shop/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView


# Создаем здесь представления.

def home(request):
    return render(request, "users/home.html")


class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/register.html"

shop/basket/templates/basket/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
  <h1>Корзина покупок</h1>
  <table class="basket">
    <thead>
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in basket %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'basket:basket_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'basket:basket_remove' product.id %}">Удалить</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">${{ basket.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">В магазин</a>
    <a href="#" class="button">Оформить заказ</a>
  </p>
{% endblock %}

shop/myshop/templates/shop/base.html
{% load static %}

<html>
<!DOCTYPE html>
<head>
<meta charset="UTF-8" />
<title>{% block title %}Online-shop{% endblock %}</title>
<link href="{% static 'css/base.css' %}" rel='stylesheet'>
</head>
<body>
<div id="header">
<a href="/" class="logo">Online-shop</a>
</div>
<div id="subheader">
    <div class="basket">
        {% with total_items=basket|length %}
        {% if basket|length > 0 %}
        В корзине:
        <a href="{% url 'basket:basket_detail' %}">
         {{ total_items }} шт ,${{ basket.get_total_price }}
         </a>
        {% else %}
        <button type="submit">Корзина пустая</button>
        {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% if messages %}
        	{% for message in messages %}
          	<div class="alert alert-{{ message.tags }}">
            	{{ message }}
          	</div>
        	{% endfor %}
{% endif %}
{% block content %}{% endblock %}
</div>
</body>
</html>

shop/myshop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static 'img/no_image.png' %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">${{ product.price }}</p>
    <form action="{% url 'basket:basket_add' product.id %}" method="post">
        {{ basket_product_form }}
        {% csrf_token %}
        <input type="submit" value="В корзину">
    </form>
{{ product.description|linebreaks }}
</div>
{% endblock %}

shop/myshop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Категория</h3>
<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Все</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Товар{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
${{ product.price }}
</div>
{% endfor %}
</div>
{% endblock %}

shop/users/templates/users/home.html
<html>
  <head>
    <style>
     body {
      color: pink;
      text-align: center;
      }

    </style>
  </head>
  <body>

    <h1>Hello, {{ user.username|default:'Guest' }}</h1>

    <p> Welcome to the Our site</p>
    <div>
      {% if user.is_authenticated %}
          <a href="{% url 'logout' %}">Logout</a>

      {% else %}
          <a href="{% url 'signup' %}">Sign Up</a>
          <a href="{% url 'login' %}">Login</a>
      {% endif %}
  </div>

  </body>
</html>